apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.0-debug
    command:
      - /busybox/sleep
      - "999999"
    tty: true
    volumeMounts:
      - name: kaniko-workspace
        mountPath: /workspace
      - name: docker-config
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-workspace
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: docker-config
